add_newline = false
format = """
[ğŸ”º](fg:#f38ba8) [CyberP0rtal](fg:#f9e2af bold) [î‚´](fg:#89b4fa) $directory$git_branch$git_status
$character"""

[directory]
truncation_length = 3
style = "bold fg:#a6e3a1"

[git_branch]
symbol = "ï˜ "
style = "fg:#f5c2e7"

[git_status]
style = "fg:#fab387"

[character]
success_symbol = "[â¯](bold fg:#a6e3a1)"
error_symbol = "[â¯](bold red)"
